image: maven:3.6.3-openjdk-14

stages:
     - build
     - test
     - package

build-production:
 stage: build
 script:
  - mvn compile
 only:
  - master
  
test-production:
 stage: test
 script:
  - mvn test
 only:
  - master

package-production:
 stage: package
 only:
  - master
 script:
  - mvn -DskipTests=true package
 artifacts:
  paths:
   - target/profile-ms.war