image: goyalzz/ubuntu-java-8-maven-docker-image

stages:
     - build
     - test
     - package

build-production:
 stage: build
 script:
  - mvn -B test --file pom.xml
 only:
  - master
  
test-production:
 stage: test
 script:
  - mvn -B test --file pom.xml
 only:
  - master

package-production:
 stage: package
 only:
  - master
 script:
  - mvn -B -DskipTests=true package --file pom.xml
 artifacts:
  paths:
   - target/profile-ms.war