version: '3'
services:
  mypostgresprofiles:
    image: postgres
    restart: always
    container_name: mypostgresprofiles
    networks:
        profilems:
          ipv4_address: 173.20.128.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=profilems
      - TZ=America/Fortaleza
  profile-ms:
    depends_on:
      - mypostgresprofiles
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-ms
    networks:
       profilems:
        ipv4_address: 173.20.128.2
    restart: always
    links:
      - mypostgresprofiles
    restart: always
    environment:
      TZ: "America/Fortaleza"
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
             echo $TZ > /etc/timezone"
    ports:
      - 8080:8081

networks:
  profilems:
    driver: bridge
    ipam:
      config:
        - subnet: 173.20.0.0/16