# This workflow will comment a Pull Request

name: Comment a Pull Request

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/labeler@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}